server:
  port: 8080

spring:
  datasource:
    #    url: jdbc:mysql://mainline.proxy.rlwy.net:24353/tienda_saas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/tienda_saas?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    #    password: ArpCGngyCGwEcLItfWCoHpcjsIxssefI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate    # Solo valida las tablas
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # === CONFIGURACIÓN PARA SUBIDA DE ARCHIVOS (IMÁGENES) ===
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 50MB
      file-size-threshold: 2MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: joseangelespinozamorales@gmail.com
    password: iincqrgsayxvotzr
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

jwt:
  secret: 8f9e2a7c1d5b3e6f4a9d8c7b6e5f4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2910
  expiration: 86400000 # 24 horas

app:
  frontend-url: http://localhost:4200