server:
  port: 8080
  tomcat:
    max-part-count: 100
    max-swallow-size: -1
    max-parameter-count: 10000

spring:
  datasource:
    url: jdbc:mysql://ballast.proxy.rlwy.net:17586/tienda_saas
    username: root
    password: JkjUeIYWtkoDPjFXCYbdHdNyrucxbqDg
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB
      file-size-threshold: 5MB

  mvc:
    formcontent:
      filter:
        enabled: false

jwt:
  secret: 8f9e2a7c1d5b3e6f4a9d8c7b6e5f4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2910
  expiration: 86400000  # 24 horas

app:
  frontend-url: http://localhost:4200